export const environment = {
  PLANTILLAS_FORMULARIOS_DINAMICOS_USER:
    process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_USER,
  PLANTILLAS_FORMULARIOS_DINAMICOS_PASS:
    process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_PASS,
  PLANTILLAS_FORMULARIOS_DINAMICOS_HOST:
    process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_HOST,
  PLANTILLAS_FORMULARIOS_DINAMICOS_PORT:
    process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_PORT,
  PLANTILLAS_FORMULARIOS_DINAMICOS_DB:
    process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_DB,
  PLANTILLAS_FORMULARIOS_DINAMICOS_HTTP_PORT:
    process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_HTTP_PORT,
  PLANTILLAS_FORMULARIOS_DINAMICOS_AUTH_DB:
    process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_AUTH_DB,
};
