export const environment = {
  USER: process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_USER,
  PASS: process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_PASS,
  HOST: process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_HOST,
  PORT: process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_PORT,
  DB: process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_DB,
  HTTP_PORT: process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_HTTP_PORT,
  AUTH_DB: process.env.PLANTILLAS_FORMULARIOS_DINAMICOS_AUTH_DB,
};
